# Import libraries
from typing import TypedDict, Annotated, Literal
from pydantic import BaseModel

from langchain_groq import ChatGroq
from langchain_core.messages import BaseMessage, SystemMessage, HumanMessage, AIMessage
from langgraph.graph import StateGraph, START, END
from langgraph.graph.message import add_messages
from langgraph.checkpoint.memory import InMemorySaver
from dotenv import load_dotenv

# Load environment variables
load_dotenv()


# Define LLM
llm = ChatGroq(model="openai/gpt-oss-120b",temperature=0.6)


# Define classifier output
class QuestionCategory(BaseModel):
    category: Literal[
        "score advice",
        "lifestyle advice",
        "general advice"
    ]


# Create structured classifier LLM
classifier_llm = llm.with_structured_output(QuestionCategory)


# Define state
class ChatState(TypedDict):

    # Conversation messages
    messages: Annotated[list[BaseMessage], add_messages]

    # Predicted mental health score
    mental_health_score: float

    # Original user data
    user_data: dict

    # Category of user question
    question_category: Literal[
        "score advice",
        "lifestyle advice",
        "general advice"
    ]

    # Analysis of predicted score
    score_analysis: str

    # Context generated by advisor
    advisor_context: str

    # Final response
    response: str


# Create prediction analyzer node
def analyze_prediction(state: ChatState):
    """Analyze the predicted mental health score."""

    # Fetch predicted score
    score = state["mental_health_score"]

    # Analyze score
    if score < 5:
        message = "Your predicted score is relatively low."
    elif score < 7:
        message = "Your predicted score is in the moderate range."
    else:
        message = "Your predicted score is relatively high."

    # Return state update
    return {
        "score_analysis": message
    }


# Create question classifier node
def classify_question(state: ChatState):
    """Classify the user's question."""

    # Fetch conversation
    messages = state["messages"]

    # Create classification prompt
    prompt = f"""
    Classify the user's latest question into exactly one category:

    - score advice
    - lifestyle advice
    - general advice

    Conversation:
    {messages}
    """

    # Get structured category from LLM
    result = classifier_llm.invoke(prompt)

    # Return state update
    return {
        "question_category": result.category
    }


# Create question routing function
def route_question(state: ChatState) -> Literal["score_advisor", "lifestyle_advisor", "general_advisor"]:
    """Route the question to the correct advisor."""

    # Fetch question category
    category = state["question_category"]

    if category == "score advice":
        return "score_advisor"

    elif category == "lifestyle advice":
        return "lifestyle_advisor"

    else:
        return "general_advisor"


# Create score advisor node
def score_advisor(state: ChatState):
    """Create context for mental health score questions."""

    # Fetch required information
    messages = state["messages"]
    score = state["mental_health_score"]
    user_data = state["user_data"]

    # Create advisor prompt
    prompt = f"""
    You are a mental health score advisor.

    Analyze the user's question using:
    Mental health score: {score}
    User data: {user_data}
    User question: {messages}

    Provide useful context that another LLM can use
    to answer the user's question.

    Do not diagnose medical conditions or provide medical advice.
    """

    # Generate advisor context
    context = llm.invoke(prompt).content

    # Return state update
    return {
        "advisor_context": context
    }


# Create lifestyle advisor node
def lifestyle_advisor(state: ChatState):
    """Create context for lifestyle questions."""

    # Fetch required information
    messages = state["messages"]
    user_data = state["user_data"]

    # Create advisor prompt
    prompt = f"""
    You are a mental health lifestyle advisor.

    Analyze the user's question using:
    User data: {user_data}
    User question: {messages}

    Provide practical lifestyle-related context
    that another LLM can use to answer the question.

    Do not diagnose medical conditions or provide medical advice.
    """

    # Generate advisor context
    context = llm.invoke(prompt).content

    # Return state update
    return {
        "advisor_context": context
    }


# Create general advisor node
def general_advisor(state: ChatState):
    """Create context for general questions."""

    # Fetch user question
    messages = state["messages"]

    # Create advisor prompt
    prompt = f"""
    You are a helpful assistant handling general questions.

    User question:
    {messages}

    Provide useful context that another LLM can use
    to answer the user's question.
    """

    # Generate advisor context
    context = llm.invoke(prompt).content

    # Return state update
    return {
        "advisor_context": context
    }


# Create final guidance generator node
def generate_guidance(state: ChatState):
    """Generate the final personalized response."""

    # Fetch required information
    messages = state["messages"]
    score = state["mental_health_score"]
    user_data = state["user_data"]
    score_analysis = state["score_analysis"]
    advisor_context = state["advisor_context"]

    # Create final response prompt
    prompt = [
        SystemMessage(content=f"""
        You are MindWell, a calm and supportive Mental Health coach andlifestyle assistant.

        Use the information below internally to answer the user's question.

        Mental health score:
        {score}

        User data:
        {user_data}

        Score analysis:
        {score_analysis}

        Advisor context:
        {advisor_context}

        Rules:
        - Give a short response, usually 3 to 6 sentences.
        - Focus only on what the user asked.
        - Do not repeat information unnecessarily.
        - Do not generate tables.
        - Do not use Markdown headings.
        - Do not use pipes, horizontal lines, or complex formatting.
        - You may use simple bullet points when useful.
        - Give 1 to 3 practical suggestions maximum.
        - Speak naturally, like a supportive coach.
        - Do not overwhelm the user with a long plan.
        - Do not diagnose medical conditions.
        - Do not provide medical advice.
        - Do not blindly repeat the advisor context. Use it only as background.
        - If the user gives their name, use it naturally.
        - End with only one or two calm, supportive emoji when appropriate.
        - Use mostly plants, flowers, and nature emojis. Avoid human, animal, or food emojis.
        """),
        *messages
    ]

    # Generate final response
    response = llm.stream(prompt)
    full_response = ""

    # Return final state update
    for chunk in response:
        full_response += chunk.content

    return {
        "response": full_response,
        "messages": [AIMessage(content=full_response)]
    }

# Define graph
graph = StateGraph(ChatState)


# Add nodes
graph.add_node("analyze_prediction", analyze_prediction)
graph.add_node("classify_question", classify_question)
graph.add_node("score_advisor", score_advisor)
graph.add_node("lifestyle_advisor", lifestyle_advisor)
graph.add_node("general_advisor", general_advisor)
graph.add_node("generate_guidance", generate_guidance)


# Add edges
graph.add_edge(START, "analyze_prediction")
graph.add_edge("analyze_prediction", "classify_question")
graph.add_conditional_edges("classify_question",route_question)
graph.add_edge("score_advisor", "generate_guidance")
graph.add_edge("lifestyle_advisor", "generate_guidance")
graph.add_edge("general_advisor", "generate_guidance")
graph.add_edge("generate_guidance", END)

# Create checkpoint
checkpoint = InMemorySaver()

# Compile graph
workflow = graph.compile(checkpointer=checkpoint)
